### ISSUE TITLE
[Room] Use hash URL instead of normal URLs for room

### ISSUE THREAD

**Issue by Elektropepi** [Debugger-Buam/Funkgeraet#33]
When deploying the web application on NGINX, its routing messes up the room URL (yields a 404 when opening localhost:8080/room). 

A cheap alternative would be using hash URLs localhost:8080/#room. Or implement the routing on NGINX (docker setup underway with https://github.com/Debugger-Buam/Funkgeraet/issues/32), good luck with that.

**Comment by maperz** [comment]
To stick to our current routing solution (without #, much cleaner)
we can configure nginx via

`location / {
    try_files $uri $uri/ /index.html;
}`
