### ISSUE TITLE
Final Submission Preparation

### ISSUE THREAD

**Issue by Elektropepi** [Debugger-Buam/Funkgeraet#44]
We need to focus now on the final submission, especially the presentation. It should include (please add if something is missing)

- [x] Complete list of all features
- [x] Complete list of all HTML5 functionality in Funkgerät
- [x] Checklist of all requirements ([slide 25-28](kti.tugraz.at/staff/vsabol/courses/wt/wt_slides_intro.pdf)) and how we implemented them for Funkgerät
- [x] Graphs how the communication works
- [x] Screenshots

Also a demo ([slide 23](kti.tugraz.at/staff/vsabol/courses/wt/wt_slides_intro.pdf)) should be prepared with happy paths
- [ ] Show us what you did
- [ ] Explain how it works shortly
- [ ] Briefly answer 1-2 questions (5 minutes)
- [ ] Justify why you did something (the way you did it)?
- [ ] Discuss advantages/disadvantages openly

Presentation should be 5 minutes long, demo should be 5 minutes long. 20 minutes for question answering.

**Comment by FlorianLes** [comment]
Demo App Presentation: https://docs.google.com/presentation/d/1zM2-BwaW5mV5tVMWlegVRBLeYWG5aCrS2J5m7dBBqZM/edit#slide=id.p
