### ISSUE TITLE
[Client] Strip CSS from JS bundle to make initial render more clean

### ISSUE THREAD

**Issue by Elektropepi** [Debugger-Buam/Funkgeraet#52]
Because CSS is in 250KByte JS in bundle, on slow networks, the page is bungled up (no font, no styles) until the bundle is finally loaded (up to 1 second!)

**Comment by maperz** [comment]
Can we fix this issue by configuring Webpack to handle SASS file transpilation and packing into a seperate css file?

**Comment by Elektropepi** [comment]
Yea done
